main:
  file_game: bf6_gameplay.mp4
  # New design pattern = Abstract factory that allows to choose which models, sources and audience to use for each step.
  # To improve accuracy, you can set multiple models of the same type for the same operation
  # NOTE: [] = empty = 'none' = skips; fallback = triggers fallback; [data] = triggers each entity named data
  workflow:
    extract-genre:
      models: fallback
      sources: none
      player: none
    get-games:
      models: none
      sources: none
      # sources: ['metacritic']
      player: none
    get-reviews:
      models: none
      sources: none
      # sources: ['metacritic']
      player: none
    do-sentiment-analysis:
      models: none
      # models: ['cardiffnlp/twitter-roberta-base-sentiment-latest']
      sources: none
      player: none
    get-trends:
      models: none
      # models: ['ml6team/keyphrase-extraction-kbir-inspec']
      sources: none
      player: none
    classify-trends:
      models: fallback
      # models: ['sentence-transformers/all-MiniLM-L6-v2']
      sources: none
      player: none
    extract-video-features:
      models: ['openai/clip-vit-base-patch32']
      sources: none
      player: none
    create-feedback-report:
      models: none
      sources: none
      player: none
# You can disable the below parameters by simply removing them.
vlm:
  use_model_finetuned: False
  testing_path: data/testing/visual/genres
  clip_resolution: 360x640
  clip_duration_seconds: 300 # We only care about the first X seconds of the video
  # batch_size: 6
  # epochs: 10
  max_num_frames: 50  # the amout of frames we want to read from the video during the clip duration set (e.g. if video has 300 frames, we are only getting 16 frames)
  device_type: cuda:0 # <device hardware accelerator>:<GPU index> (nvidia)
  device_debug: 1 # show device operations when running visual models, incl. changes on images/video frames
llm:
  use_model_finetuned: False
  device_debug: 1 # show device operations when running text models
local:
  scripts:
    apis: none
    internal:
      ffmpeg:
        audio-codec: aac
        audio-bitrate: 128k
        video-codec: h264
        video-bitrate: 500k
    path: tools/local/scripts
  # sources:
  #   games:
  #   - name: metacritic
  #     is_enabled: True
  #   trends: none
  #   feedback:
  #     reviews: none
  #     comments: none
  #     scores: none
  cache:
    path: data/cache/ 
    ignore_warning: False # in case reload/reset the cache memory is called
# We can also force the fallback by disabling all of the entities type (model, source or player)
models:
  video_feature_extraction:
    environment:
    - repository: ultralytics
      name: torch-hub-yolov5s
      is_local: False
      is_enabled: False
      confidence_threshold: 0.5
    movement:
    - repository: none
      name: none
      is_local: False
      is_enabled: False
      confidence_threshold: 0.5
    object:
    - repository: facebook
      name: detr-resnet-50
      is_local: False
      is_enabled: False
      confidence_threshold: 0.5
  video_classification:
  - repository: pytorch
    name: x3d-xs
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
  - repository: openai
    name: clip-vit-base-patch32
    is_local: False
    is_enabled: True
    confidence_threshold: 0.5
  conversation: # text generation/chatbots
  - repository: meta-llama
    name: Meta-Llama-3.1-8B-Instruct
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
  - repository: openai-community
    name: gpt2
    is_local: False
    is_enabled: True
    confidence_threshold: 0.5
  translation:
  - repository: google
    name: mt5-base
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
  - repository: facebook
    name: nllb-200-distilled-600M
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
  sentiment_analysis:
  - repository: cardiffnlp
    name: twitter-roberta-base-sentiment-latest
    is_local: False
    is_enabled: True
    confidence_threshold: 0.5
    max_length: 512 # max number of characters/tokens for roberta models. If it is above, it truncates the text
  named_entity_recognition:
  - repository: dbmdz
    name: test
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
  summarization:
  - repository: google
    name: pegasus-xsum
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
    max_length: 512 # max number of characters/tokens for roberta models. If it is above, it truncates the text
    min_length: 20 # less than this, makes it harder for the model to get the context
  text_feature_extraction:
  - repository: ml6team
    name: keyphrase-extraction-kbir-inspec
    is_local: False
    is_enabled: True
    confidence_threshold: 0.5
  - repository: sentence-transformers
    name: all-MiniLM-L6-v2
    is_local: False
    is_enabled: True
    confidence_threshold: 0.5
  text_classification:
  - repository: facebook
    name: bart-large-mnli
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
  - repository: microsoft
    name: deberta-v3-base
    is_local: False
    is_enabled: False
    confidence_threshold: 0.5
  question_answer:
  - repository: deepset
    name: roberta-base-squad2
    is_local: False
    is_enabled: True
    confidence_threshold: 0.5
  hugging_face_token: YOUR_HUGGING_FACE_TOKEN
sources:
  external:
    apis:
    - publisher: google
      name: youtube
      token: YOUR_YOUTUBE_API_TOKEN
      video_published_before_days: 10
      max_number_attempts: 5
      is_simple_query: True
      is_enabled: True
    websites:
    - name: metacritic
      is_enabled: True
  internal:
    databases:
    - name: sqlite3
      is_enabled: False
      storage: sqlite_player_feedback.db
    path: data/database/
player:
  personality: ""  # Available: [happy, sad, frustrated, optimistic]
  age_group: ""  # Available: [young > teen > adult > old]
  location: ""  # Available: [Region > Country > Continent]
  gender: ""  # Available: [female, male]
report:
  path: data/output
  score:
    gameplay: 12.5
    graphics: 12.5
    sound: 12.5
    story: 12.5
    content: 12.5
    ui: 12.5
    technical: 12.5
    social: 12.5