main:
  file_game: game1.mp4
  bot:
    personality: ""  # Available: [happy, sad, frustrated, optimistic]
    age_group: ""  # Available: [young > teen > adult > old]
    location: ""  # Available: [Region > Country > Continent]
    gender: ""  # Available: [female, male]
vlm:
  models:
    genre:
      name: x3d
      version: xs
      is_local: False
    environment: 
      repository: openai/CLIP
      name: clip_resnet50
    movement:
      repository: facebookresearch/pytorchvideo
      name: slowfast_r50
    object:
      name: yolo
      version: v5s
      is_local: False
  use_model_finetuned: True
  testing_path: data/testing/visual/genres
llm:
  model: llama3.2
  number_of_games: 2
local:
  ffmpeg:
    audio-codec: aac
    audio-bitrate: 128k
    video-codec: h264
    video-bitrate: 500k
apis:
  google:
    youtube-key: YOUR_YOUTUBE_API_TOKEN
    video_published_before_days: 10
    max_number_attempts: 5
    is_simple_query: True
