import matplotlib.pyplot as plt
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
import argparse
import sys
from innovation.FeedbackerAi.tools.local.utilities import Utility
from typing import Optional, Dict, Any, List
import ast
import json

# This script is mainly focused on creating a PDF report with graphs and tables. The input data should follow this structure (ordered):
# return {
#     "title": title,
#     "data": [
#         {"table": "TO ADD", "data": to_have_trends},
#         {"table": "TO REMOVE", "data": not_to_have_trends},
#         {"graphs": "Images", "data": []},
#         {"section": "Summary", "data": [{"text": "Final score", "data": final_score}]},
#         {"section": "Details", "data": [
#             {"text": "most_demanded_feature", "data": most_demanded_feature},
#             {"text": "least_demanded_feature", "data": least_demanded_feature},
#             {"text": "most_provided_feature", "data": most_provided_feature},
#             {"text": "least_provided_feature", "data": least_provided_feature},
#             {"text": "most_hated_feature", "data": most_hated_feature},
#             {"text": "least_hated_feature", "data": least_hated_feature},
#             {"text": "most_damaging_feature", "data": most_damaging_feature},
#             {"text": "least_damaging_feature", "data": least_damaging_feature}
#         ]},
#         {"section": "Footer", "data": [{"text": None, "data": "Generated by Feedbacker AI"}]}
#     ]
# }
# styles_config = {
#   "title_font": "Helvetica-Bold",
#   "title_size": 24,
#   "body_font": "Helvetica",
#   "body_size": 12
# }
# The output pdf file is expected to have this format:
# TITLE
# TABLE
# IMAGES
# OTHER (sections, text, etc...)


class TimeoutExpired(Exception):
    pass

class SubprocessError(Exception):
    pass

# 1. Generate a sample plot with Matplotlib and save as image
def create_image(filename):
    plt.figure(figsize=(4, 3))
    plt.plot([1, 2, 3, 4], [10, 20, 25, 30], marker='o')
    plt.title('Sample Graph')
    plt.savefig(filename)
    plt.close()

def append_header(section_title, story, styles, styles_config):
    # Section Header
    section_style = styles['Heading2']
    section_style.fontName = styles_config["body_font"]
    section_style.fontSize = styles_config["body_size"] + 2
    story.append(Paragraph(section_title, section_style))
    story.append(Spacer(1, styles_config["content_spacing"]))
    return story
    
def create_story(title, data: List[Dict], styles_config):
    story = []
    styles = getSampleStyleSheet()
    
    # Add Title
    title_style = styles['Title']
    title_style.fontName = styles_config["title_font"]
    title_style.fontSize = styles_config["title_size"]
    title_style.alignment = 1  # Center

    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, styles_config["title_size"]))    
    
    # Add the table section
    story = append_header("Data", story, styles, styles_config)
    
    for data_index, data_item in enumerate(data):
        if "table" in data_item.keys() and data_item["data"]:
            df = data_item["data"]

            # If your JSON is a list of dicts, you might want headers
            if isinstance(df, list):
                if df and isinstance(df[0], dict):
                    headers = list(df[0].keys())
                    table_data = [headers]
                    for item in df:
                        row = [item.get(header, "") for header in headers]
                        table_data.append(row)
                else:
                    # data is a list of lists or simple values
                    table_data = df
            else:
                # Handle other structures if needed
                table_data = [[str(df)]]
            
            # Create table
            table = Table(table_data)
            table.setStyle(TableStyle(styles_config["table"]))
            story.append(table)
            continue
        
        # Add the graph image section
        # story = append_header("Graphs", story, styles, styles_config)
        if "graph" in data_item.keys() and data_item["data"]:
            graph = data_item['data']
            image = create_image(graph["title"])
            story.append(Image(image, width=styles_config["image_resolution"][0], height=styles_config["image_resolution"][1]))
            story.append(Spacer(1, 12))
            continue
        
        # Add content sections / extra details
        # story = append_header("Details", story, styles, styles_config)
        if "section" in data_item.keys() and data_item["data"]:
            for paragraph in data_item["data"]:
                section_title = paragraph['text']
                section_text = paragraph['data']
            
                story = append_header(section_title, story, styles, styles_config)
                
                # Section Text
                body_style = styles['Normal']
                body_style.fontName = styles_config["body_font"]
                body_style.fontSize = styles_config["body_size"]
                story.append(Paragraph(section_text, body_style))
                story.append(Spacer(1, styles_config["section_spacing"]))
        
    return story

def create_styles_config(data: Dict=None):
    
    styles_config = {
        'title_font': 'Helvetica-Bold',
        'title_size': 24,
        'body_font': 'Helvetica',
        'body_size': 12,
        'section_spacing': 12,
        'content_spacing': 6,
        'table': [
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
        ],
        'image_resolution': (400, 300) # widthxheight
    }
    if data:
        styles_config.update(data)
        
    return styles_config
    
    
def main():
    parser = argparse.ArgumentParser(description='PDF Report Tool')
    parser.add_argument('filepath', type=str, help='Path of file and filename for the output')
    parser.add_argument('reportdata', type=str, help='Text data for each type of object as a dictionary')
    parser.add_argument('--styles_config', type=str, help='Custom style for each type of object as a dictionary')

    args = parser.parse_args()
    output_path = Utility.get_project_directory(args.filepath)
    reportdata = Utility.read_json_from_file(args.reportdata)
    styles_config =  Utility.read_json_from_file(args.reportdata) if args.styles_config else None
    
    if styles_config:
        Utility.remove_file(args.styles_config)
    if reportdata:
        Utility.remove_file(args.reportdata)
    
    try: 

        doc = SimpleDocTemplate(output_path, pagesize=letter)
        styles_config = create_styles_config(styles_config)
            
        story = create_story(reportdata["title"], reportdata["data"], styles_config)
        
        # Build PDF
        doc.build(story)

        if not Utility.does_file_exist(output_path):
            raise SubprocessError("File was not created correclty!")
            
    except Exception as ex:
        Utility.remove_file(output_path)
        print(f"An error occurred in generating the pdf report in {output_path}: {ex}", file=sys.stderr)
        sys.exit(1)

    print(f"Report generated: {output_path}")
    sys.exit(0)

if __name__ == "__main__":
    main()

